"""services_and_requirements

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-11 20:32:38.214050

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("service_type", sa.String(length=1), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("base_fee", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("service_type IN ('A', 'B', 'C')", name="chk_service_type"),
        sa.CheckConstraint("base_fee >= 0", name="chk_service_base_fee_positive"),
        sa.CheckConstraint("retention_days >= 0", name="chk_service_retention_days_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_services_is_active"), "services", ["is_active"], unique=False)
    op.create_index(op.f("ix_services_service_type"), "services", ["service_type"], unique=False)

    op.create_table(
        "service_interaction_requirements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("max_missed_attempts", sa.Integer(), nullable=False, server_default="3"),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.CheckConstraint(
            "max_missed_attempts >= 1", name="chk_interaction_req_max_missed_attempts"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "service_document_requirements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("is_reusable", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("max_file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.CheckConstraint("max_file_size_bytes > 0", name="chk_doc_req_max_file_size_positive"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service_id", "name", name="uq_service_doc_req_name"),
    )

    op.create_table(
        "service_requirement_allowed_file_types",
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_id"], ["service_document_requirements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("requirement_id", "mime_type"),
    )

    op.create_table(
        "centre_supported_services",
        sa.Column("centre_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("centre_fee_override", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "centre_fee_override >= 0", name="chk_centre_supported_service_fee_override"
        ),
        sa.ForeignKeyConstraint(
            ["centre_id"],
            ["akshaya_centres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("centre_id", "service_id"),
    )
    op.create_index(
        op.f("ix_centre_supported_services_service_id"),
        "centre_supported_services",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        "ix_centre_supported_services_centre_id_is_active",
        "centre_supported_services",
        ["centre_id", "is_active"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_centre_supported_services_centre_id_is_active", table_name="centre_supported_services"
    )
    op.drop_index(
        op.f("ix_centre_supported_services_service_id"), table_name="centre_supported_services"
    )
    op.drop_table("centre_supported_services")
    op.drop_table("service_requirement_allowed_file_types")
    op.drop_table("service_document_requirements")
    op.drop_table("service_interaction_requirements")
    op.drop_index(op.f("ix_services_service_type"), table_name="services")
    op.drop_index(op.f("ix_services_is_active"), table_name="services")
    op.drop_table("services")
    # ### end Alembic commands ###
