"""Add is_archived_by_citizen to ServiceRequest

Revision ID: 0c67afc0b3d2
Revises: 2e2eb0d81396
Create Date: 2026-09-23 06:18:07.986224+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c67afc0b3d2'
down_revision: Union[str, None] = '2e2eb0d81396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('is_archived_by_citizen', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'is_archived_by_citizen')
    # ### end Alembic commands ###
