"""escalations

Revision ID: 12144d8bce31
Revises: 0012
Create Date: 2026-09-13 08:12:55.115583+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12144d8bce31'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_escalations_is_resolved', 'request_escalations', ['is_resolved'], unique=False)
    op.create_index('ix_request_escalations_request_id', 'request_escalations', ['request_id'], unique=False)
    op.drop_index(op.f('ix_centre_supported_services_centre_id_is_active'), table_name='centre_supported_services')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_centre_supported_services_centre_id_is_active'), 'centre_supported_services', ['centre_id', 'is_active'], unique=False)
    op.drop_index('ix_request_escalations_request_id', table_name='request_escalations')
    op.drop_index('ix_request_escalations_is_resolved', table_name='request_escalations')
    op.drop_table('request_escalations')
    # ### end Alembic commands ###
