"""Add requirement_type and document status

Revision ID: 2e2eb0d81396
Revises: aadaff482c3a
Create Date: 2026-09-21 11:16:30.940552+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e2eb0d81396'
down_revision: Union[str, None] = 'aadaff482c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('request_documents', sa.Column('status', sa.String(length=40), nullable=False))
    op.add_column('request_documents', sa.Column('employee_remarks', sa.Text(), nullable=True))
    op.add_column('request_documents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('request_documents', sa.Column('verified_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_request_documents_verified_by_id_users', 'request_documents', 'users', ['verified_by_id'], ['id'])
    op.add_column('service_document_requirements', sa.Column('requirement_type', sa.String(length=20), nullable=False))
    op.add_column('service_document_requirements', sa.Column('conditional_rule', sa.Text(), nullable=True))
    op.add_column('service_document_requirements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_document_requirements', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('service_document_requirements', 'is_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_document_requirements', sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('service_document_requirements', 'updated_at')
    op.drop_column('service_document_requirements', 'created_at')
    op.drop_column('service_document_requirements', 'conditional_rule')
    op.drop_column('service_document_requirements', 'requirement_type')
    op.drop_constraint('fk_request_documents_verified_by_id_users', 'request_documents', type_='foreignkey')
    op.drop_column('request_documents', 'verified_by_id')
    op.drop_column('request_documents', 'verified_at')
    op.drop_column('request_documents', 'employee_remarks')
    op.drop_column('request_documents', 'status')
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
