"""Update profile models

Revision ID: 672f0cc42efd
Revises: d78e998be27c
Create Date: 2026-09-30 05:41:29.778325+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672f0cc42efd'
down_revision: Union[str, None] = 'd78e998be27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('citizen_profiles', sa.Column('gender', sa.String(length=16), nullable=True))
    op.add_column('citizen_profiles', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('citizen_profiles', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('citizen_profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('citizen_profiles', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('citizen_profiles', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('citizen_profiles', sa.Column('pin_code', sa.String(length=16), nullable=True))
    op.drop_column('citizen_profiles', 'address_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen_profiles', sa.Column('address_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('citizen_profiles', 'pin_code')
    op.drop_column('citizen_profiles', 'state')
    op.drop_column('citizen_profiles', 'district')
    op.drop_column('citizen_profiles', 'city')
    op.drop_column('citizen_profiles', 'address_line2')
    op.drop_column('citizen_profiles', 'address_line1')
    op.drop_column('citizen_profiles', 'gender')
    op.drop_column('citizen_profiles', 'date_of_birth')
    # ### end Alembic commands ###
