"""Add phone to employee profile

Revision ID: 9f14adbaac1b
Revises: 672f0cc42efd
Create Date: 2026-09-30 05:42:13.438319+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f14adbaac1b'
down_revision: Union[str, None] = '672f0cc42efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'phone')
    # ### end Alembic commands ###
