""" add_photo_url

Revision ID: cad6b58eebb5
Revises: 845ec9ce2a98
Create Date: 2026-10-06 01:56:06.849827+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cad6b58eebb5'
down_revision: Union[str, None] = '845ec9ce2a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizen_profiles', sa.Column('address_text', sa.Text(), nullable=True))
    op.drop_column('citizen_profiles', 'address_line1')
    op.drop_column('citizen_profiles', 'city')
    op.drop_column('citizen_profiles', 'gender')
    op.drop_column('citizen_profiles', 'pin_code')
    op.drop_column('citizen_profiles', 'date_of_birth')
    op.drop_column('citizen_profiles', 'address_line2')
    op.drop_column('citizen_profiles', 'district')
    op.drop_column('citizen_profiles', 'state')
    op.add_column('employee_profiles', sa.Column('photo_url', sa.String(length=512), nullable=True))
    op.drop_column('employee_profiles', 'phone')
    op.drop_column('users', 'notification_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'{"request_updates": true, "service_updates": true, "system": true}\'::json'), autoincrement=False, nullable=False))
    op.add_column('employee_profiles', sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('employee_profiles', 'photo_url')
    op.add_column('citizen_profiles', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('citizen_profiles', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('citizen_profiles', sa.Column('address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('citizen_profiles', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('citizen_profiles', sa.Column('pin_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('citizen_profiles', sa.Column('gender', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('citizen_profiles', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('citizen_profiles', sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('citizen_profiles', 'address_text')
    # ### end Alembic commands ###
