"""Add notification_preferences to users

Revision ID: d78e998be27c
Revises: 845ec9ce2a98
Create Date: 2026-09-30 05:33:15.333471+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78e998be27c'
down_revision: Union[str, None] = '845ec9ce2a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_preferences', sa.JSON(), server_default='{"request_updates": true, "service_updates": true, "system": true}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    # ### end Alembic commands ###
