"""add_fee_fields_to_output

Revision ID: fd1e155c8698
Revises: cad6b58eebb5
Create Date: 2026-10-06 04:30:07.836805+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1e155c8698'
down_revision: Union[str, None] = 'cad6b58eebb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_outputs', sa.Column('fee_collected', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('completed_outputs', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('completed_outputs', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_outputs', 'note')
    op.drop_column('completed_outputs', 'amount')
    op.drop_column('completed_outputs', 'fee_collected')
    # ### end Alembic commands ###
